version: '3.7'

services:
  s1_m0lecoin_redis:
    image: redis:alpine
    container_name: s1_m0lecoin_redis
    restart: unless-stopped
#    ports:
#      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - s1_redis_persistent:/data
    command: redis-server --save 5 1 --loglevel warning
    networks:
      - s1_m0lecoin_subnet
  s1_m0lecoin_otp_oracle:
    build: .
    container_name: s1_m0lecoin_otp_oracle
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - s1_m0lecoin_redis
    networks:
      - s1_m0lecoin_subnet

volumes:
  s1_redis_persistent:
    driver: local

networks:
  s1_m0lecoin_subnet:
    driver: bridge
